CARGO_LIB = target/libpwrm_ffi.a

$(CARGO_LIB):
	echo `pwd`
	cp libpwrm_ffi.a /mnt/c/Work/pwr_meter_workspace/pwr_meter/apps/pwrmeter/bin/unwd-power-meter/rtest.a

.PHONY: $(CARGO_LIB)

include $(RIOTBASE)/Makefile.base
